name = "stader-graph-dashboard"
compatibility_date = "2023-12-01"
send_metrics = true

[vars]
DATA_CACHE_ENABLED = true
DATA_CACHE_NAME = "stader-graph-dashboard-api-cache"

[[d1_databases]]
binding = "DB"
database_name = "stader-graph-db"
database_id = "dede7604-bf77-45c3-abe1-b272f711f6c9"

# Sync database with subgraph every day at 00:01
[triggers]
crons = ["1 0 * * *"]

[placement]
mode = "smart"
